name: Build Monkeytype frontend.

on:
  push:
    branches: 
        - main
  workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setups Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
        - name: Run npm install
        run: npm install
        - name: Build using vite.
        run : npm run build
        - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist
        
